# Setup
title:        Maddy's Blogs
tagline:      My Latest Blog Posts
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Maddy Anand
  url:        http://maddymaster.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown